package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@CrossOrigin(origins = "*")
@RequestMapping(path="/crimes") // This means URL's start with /demo (after Application path)
public class CrimeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CrimeRepository crimeRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Crime> getAllCrimes() {
        // This returns a JSON or XML with the users
        return crimeRepository.findAll();
    }

    @PostMapping("/add")
    @ResponseBody
    public String postCrime(@RequestBody CrimeRequest request) {
        Crime crime = new Crime();
        crime.setType(request.getType());
        crime.setLocation(request.getLocation());
        crimeRepository.save(crime);
        return "Saved";
    }
}