package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@CrossOrigin(origins = "*")
@RequestMapping(path="/crimetypes") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CrimeTypeRepository crimeTypeRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<CrimeType> getAllUsers() {
        // This returns a JSON or XML with the users
        return crimeTypeRepository.findAll();
    }
}